In [37]:
# Environment
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
import utils
warnings.simplefilter("ignore")

In [38]:
# Data Loading - R 
path = "xml_folder/working_txt/right/"
Data_Right = utils.to_pd(path)
print(Data_Right[0])

['z', 'E4', 'A4', 'C5', 'B4', 'E4', 'B4', 'D5', 'C5', 'C5', 'E5', 'E5', 'G#4', 'G#4', 'E5', 'E5', 'A4', 'E4', 'A4', 'C5', 'B4', 'E4', 'B4', 'D5', 'C5', 'C5', 'A4', 'A4', 'z', 'z', 'z', 'z', 'z', 'E5', 'C5', 'E5', 'A4', 'C5', 'E4', 'G4', 'F4', 'F4', 'A4', 'A4', 'D5', 'D5', 'F5', 'F5', 'z', 'D5', 'B4', 'D5', 'G4', 'B4', 'D4', 'F4', 'E4', 'E4', 'G4', 'G4', 'C5', 'C5', 'E5', 'E5', 'z', 'C5', 'A4', 'C5', 'F4', 'F4', 'D5', 'D5', 'z', 'B4', 'G4', 'B4', 'E4', 'E4', 'C5', 'C5', 'z', 'A4', 'F4', 'A4', 'D4', 'D4', 'B4', 'B4', 'C5', 'C5', 'z', 'z', 'z', 'z', 'z', 'z', 'z', 'G4', 'C5', 'E5', 'D5', 'G4', 'D5', 'F5', 'E5', 'E5', 'G5', 'G5', 'B4', 'B4', 'G5', 'G5', 'C5', 'G4', 'C5', 'E5', 'D5', 'G4', 'D5', 'F5', 'E5', 'E5', 'C5', 'C5', 'G5', 'G5', 'E5', 'E5', 'C6', 'A5', 'E5', 'A5', 'C5', 'E5', 'A4', 'C5', 'D5', 'D5', 'F#5', 'F#5', 'A5', 'A5', 'C6', 'C6', 'B5', 'G5', 'D5', 'G5', 'B4', 'D5', 'G4', 'B4', 'C5', 'C5', 'E5', 'E5', 'G5', 'G5', 'B5', 'B5', 'A5', 'F#5', 'D#5', 'F#5', 'B4', 'D#5', 'F#4', 'A4',

In [39]:
# Data Loading - L
path = "xml_folder/working_txt/left/"
Data_Left = utils.to_pd(path)

In [40]:

Data_Right_Combined = []

for notes in Data_Right:
    Data_Right_Combined.extend(notes)

Df_Right_Combined = pd.DataFrame({'notes': Data_Right_Combined})
Df_Right_Combined


notes
0         z
1        E4
2        A4
3        C5
4        B4
...     ...
12379   A#3
12380   A#3
12381   A#3
12382   A#3
12383   A#3

[12384 rows x 1 columns]

In [62]:
# Data Loading - L
# Load Data_left which is a list of list of notes


Data_Left_Combined = []

for notes in Data_Left:
    Data_Left_Combined.extend(notes)

Df_Left_Combined = pd.DataFrame({'notes': Data_Left_Combined})
Data_Left_Combined

['A2',
 'A2',
 'A3',
 'A3',
 'A3',
 'A3',
 'G#3',
 'G#3',
 'A3',
 'E3',
 'A3',
 'C4',
 'B3',
 'E3',
 'B3',
 'D4',
 'C4',
 'C4',
 'A3',
 'A3',
 'G#3',
 'G#3',
 'E3',
 'E3',
 'A3',
 'E3',
 'A3',
 'C4',
 'B3',
 'E3',
 'B3',
 'D4',
 'C4',
 'C4',
 'A3',
 'A3',
 'C4',
 'C4',
 'A3',
 'A3',
 'D4',
 'A3',
 'F3',
 'A3',
 'D3',
 'F3',
 'A2',
 'C3',
 'B2',
 'B2',
 'D3',
 'D3',
 'G3',
 'G3',
 'B3',
 'B3',
 'C4',
 'G3',
 'E3',
 'G3',
 'C3',
 'E3',
 'G2',
 'B2',
 'A2',
 'A2',
 'C3',
 'C3',
 'D3',
 'F3',
 'B2',
 'D3',
 'G2',
 'G2',
 'B2',
 'B2',
 'C3',
 'E3',
 'A2',
 'C3',
 'F2',
 'F2',
 'D2',
 'D2',
 'F2',
 'G3',
 'F3',
 'G3',
 'C3',
 'G3',
 'C4',
 'E4',
 'D4',
 'G3',
 'D4',
 'F4',
 'E4',
 'E4',
 'C4',
 'C4',
 'B3',
 'B3',
 'G3',
 'G3',
 'C4',
 'G3',
 'C4',
 'E4',
 'D4',
 'G3',
 'D4',
 'F4',
 'E4',
 'E4',
 'C4',
 'C4',
 'z',
 'z',
 'z',
 'z',
 'z',
 'G4',
 'E4',
 'G4',
 'C4',
 'E4',
 'G3',
 'B3',
 'A3',
 'A3',
 'C4',
 'C4',
 'E4',
 'E4',
 'G4',
 'G4',
 'F#4',
 'A4',
 'D4',
 'F#4',
 'A3',
 'D4',
 'F#3

In [42]:
print(Df_Right_Combined.shape)
print(Df_Left_Combined.shape)

(12384, 1)
(12384, 1)


In [43]:
# Featuring Engineering
from sklearn.preprocessing import OneHotEncoder

OHE = OneHotEncoder(sparse_output=False)
Data_Right_OHE = OHE.fit_transform(Df_Right_Combined)
Data_Right_OHE.shape



(12384, 126)

In [44]:
# train_test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(Data_Right_OHE, 
                                                    Df_Left_Combined, test_size=0.2)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(9907, 126)
(2477, 126)
(9907, 1)
(2477, 1)


In [45]:
# Model - RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier(max_features=None, n_estimators=140)
Model_RFC = RFC.fit(X_train, y_train)
Model_RFC

RandomForestClassifier(max_features=None, n_estimators=140)

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, Model_RFC.predict(X_test))

0.19136051675413807

In [60]:
import pickle

# Save the model
with open('model.pkl', 'wb') as model_file:
    pickle.dump(Model_RFC, model_file)

In [61]:
# save the list that holds all the training data 

with open('training_input.pkl', 'wb') as file:
    pickle.dump(Data_Right_Combined, file)

In [48]:
Left = Model_RFC.predict(X_test)
Left

array(['z', 'z', 'z', ..., 'z', 'F#3', 'z'], dtype=object)

In [49]:
df = pd.DataFrame(Left, columns=["L"])
df

L
0       z
1       z
2       z
3       z
4       z
...   ...
2472    z
2473    z
2474    z
2475  F#3
2476    z

[2477 rows x 1 columns]

In [50]:
decode = OHE.inverse_transform(X_test)

In [51]:
a = decode.reshape(-1)

In [52]:
List = [i for i in a]

In [53]:
df["R"] = List

In [54]:
df

L     R
0       z    B4
1       z     z
2       z    C5
3       z    A4
4       z    D6
...   ...   ...
2472    z    D5
2473    z    A4
2474    z    F5
2475  F#3  D5B5
2476    z    A4

[2477 rows x 2 columns]

In [55]:
# saving the dataframe
df.to_csv('result.csv')

In [56]:

path = "xml_folder/working_txt/right/right_Menuet_-_g-minor__J.S.Bach.musicxml.txt"
Predict_Data_Right = utils.to_pd_single(path)
Predict_Data_Right

[      column
 0        A#5
 1        A#5
 2        A#5
 3        A#5
 4         A5
 ..       ...
 379  A#3D4G4
 380  A#3D4G4
 381  A#3D4G4
 382  A#3D4G4
 383  A#3D4G4
 
 [384 rows x 1 columns]]

In [57]:
missing_notes = []

In [58]:
print(Data_Right_OHE)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [59]:

Data_Right_OHE = OHE.transform(test_Right)
Data_Right_OHE.shape

NameError: name 'test_Right' is not defined